### ISSUE TITLE
Broken 1.3.0 & 1.4.0 releases

### ISSUE THREAD

**Issue by colinschoen** [brunns/mbtest#13]
Hi Simon,

I think a mistake may have been made when cutting a release for `mbtest` `1.3.0` and `1.4.0`. 

https://github.com/brunns/mbtest/compare/1.2.0..1.4.0

Notice that python2.7 support is removed however the `1.x-backports-2.7-compatible` branch looks good: 

https://github.com/brunns/mbtest/blob/1.x-backports-2.7-compatible/setup.py#L50

**Comment by brunns** [comment]
Weird. Thanks - I'll look into it.

**Comment by brunns** [comment]
https://github.com/brunns/mbtest/compare/1.2.0..1.4.1 look OK to me.

**Comment by colinschoen** [comment]
Thanks for the quick fix!
