### ISSUE TITLE
Feature request - use library without a local Mountebank installation

### ISSUE THREAD

**Issue by vicusbass** [brunns/mbtest#16]
The library does not work without a local installation, this can be a drawback in CI/CD environments where a docker based configuration is preferable.

**Comment by brunns** [comment]
Sounds reasonable. To be clear - you'd be specifying the hostname and port for an already running instance of mountebank?

**Comment by vicusbass** [comment]
@brunns Exactly, sorry for the not-so-clear requirements. I was thinking to submit a PR myself, still thinking about that :)

**Comment by brunns** [comment]
Oh, cool, that would be great.

I was thinking of making [`MountebankServer`](https://github.com/brunns/mbtest/blob/master/src/mbtest/server.py#L32) an [ABC](https://docs.python.org/3/library/abc.html), perhaps. The existing behavior would be one concrete implementation, and a new attach-to-existing-server version could be another.

**Comment by vicusbass** [comment]
Definetely, that approach would open it for further extension

**Comment by brunns** [comment]
As of 2.3, you can attach to a running server with the MountebankServer class.

**Comment by brunns** [comment]
And as of 2.4, you can specify the server host.
