### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by colinschoen** [brunns/mbtest#3]
Are you set on dropping Python 2.7 support? I'd be happy to help maintain this if you are willing to keep it.

**Comment by brunns** [comment]
Well, [Winter is coming](https://pythonclock.org/), so I think the 2.x line should stay Python 3 only. Also going Python 3 only simplified things quite a bit in an upstream dependency. But, I'd be happy to cut a 1.x branch, backport bug fixes and some new features, and release from there.

**Comment by colinschoen** [comment]
That would be fantastic!!

**Comment by brunns** [comment]
I've cut a `1.x-backports-2.7-compatible` branch.

**Comment by colinschoen** [comment]
Thanks for doing this!
