### ISSUE TITLE
Minor version release to include support for PATCH in predicates

### ISSUE THREAD

**Issue by garry-jeromson** [brunns/mbtest#41]
Support for PATCH requests in HTTP predicates was merged a few days after the last release (https://github.com/brunns/mbtest/pull/22) - are there plans for a new release version any time soon? Would be super useful for us to have this functionality included from a PyPi release, rather than having to install it via Git.

Cheers,

Garry

**Comment by brunns** [comment]
I was waiting for https://github.com/brunns/mbtest/pull/37 to land, but that's going fairly slowly, so yeah, I should should probably go ahead with a release.

**Comment by brunns** [comment]
2.6 released.

**Comment by garry-jeromson** [comment]
Awesome. Thanks a lot!
