### ISSUE TITLE
Create a Imposter with Config File

### ISSUE THREAD

**Issue by 3wweiweiwu** [brunns/mbtest#44]
Hello,

Thank you so much for developing this wonderful library! I want to know if there is anyway to create Imposter with config file?

I try to parse in the config file as json object via from_structure but it did not work for me.

`    with open(f'C:\\Users\\wuwei\\test-sv\\test\\imposters\\test.json') as f:
        data = json.load(f)

    imposter = Imposter.from_structure(data['imposters'])`

And this is my config file
`{
    "imposters" : [{
        "port": 1001,
        "protocol": "https",
        "name": "Tutorial",
        "stubs": [{
            "predicates" : [{
                "equals": {
                    "method": "GET",
                    "path": "/tutorial"
                }
            }],
            "responses" : [{
                "is": {
                    "statusCode": 200,
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "body": { "message": "success" }
                }
            }]}
        ]
    }]
}`

**Comment by brunns** [comment]
There are a couple of problems here. Firstly, the outer `impostors` object contains an _array_ of impostors, not a single impostor. The `Imposter.from_structure()` method is designed to take the impostor structure itself, not an array of them, so try `Imposter.from_structure(data['imposters'][0])`.

Secondly, your response is missing a [`_mode`](http://www.mbtest.org/docs/protocols/http#content:~:text=HTTP%20Responses). I've treated this as mandatory - perhaps I shouldn't - but for now if you add `"_mode": "text",` to your response, you should be good.

**Comment by brunns** [comment]
I've added [a test for this](https://github.com/brunns/mbtest/commit/e4763fa2706b090801d52ac860a07a99ed120ec8).

**Comment by brunns** [comment]
Note that this test uses `http` - I need to get around to checking that [`https`](http://www.mbtest.org/docs/protocols/https) can be set up correctly.

**Comment by 3wweiweiwu** [comment]
Got it. Thank you so much for your test. This is very helpful!
