### ISSUE TITLE
Issue with MountebankServer.query_all_imposters()

### ISSUE THREAD

**Issue by jbackman** [brunns/mbtest#52]
it seems that when parsing the response of a mountebank imposter, it is expected that if a body is provided, a mode will also exist https://github.com/brunns/mbtest/blob/ef7b87532c02ac47884dd6e6f5d834066a3650c9/src/mbtest/imposters/responses.py#L77  This is not always the case. If you submit the body as JSON, it does not require a mode and thus the mode is not provided. This causes the following issue when calling` list(MountebankServer.query_all_imposters())`

```python
cls = <class 'mbtest.imposters.responses.HttpResponse'>, inner = {'body': {'hostname': '${HOSTNAME}'}, 'statusCode': 200}

    @classmethod
    def from_structure(cls, inner: JsonStructure) -> "HttpResponse":
        response = cls()
        if "body" in inner:
            response._body = inner["body"]
>       response.mode = Response.Mode(inner["_mode"])
E       KeyError: '_mode'
```

**Comment by jbackman** [comment]
https://github.com/brunns/mbtest/pull/53 to fix this

**Comment by brunns** [comment]
Good spot, thanks.

**Comment by jbackman** [comment]
This can be closed since the issue was addressed

**Comment by brunns** [comment]
2.8.1 released.
