### ISSUE TITLE
Allow modification of an existing mountebank server

### ISSUE THREAD

**Issue by jbackman** [brunns/mbtest#54]
The `MountebankServer` allows addition of imposters to an already running Mountebank mock server, but does not have the ability to update or add to existing stubs or services. 

It would be useful to be able to read the configuration of an existing mountebank mock server (which  `MountebankServer .query_all_imposters()` can already do) and set that as the `MountebankServer._running_imposters`. This would allow manipulation of existing impostors as well as addition of new stubs to existing impostors,

**Comment by jbackman** [comment]
> Interesting. I'd probably rather have explicit methods for adding and deleting stubs, and for replacing the stubs wholesale, rather than fiddling with `MountebankServer._running_imposters` - or maybe make it a public property, but make it a `List` subclass, so I could make the calls to the server when stubs are [added](https://www.mbtest.org/docs/api/overview#add-stub) or [removed](https://www.mbtest.org/docs/api/overview#delete-stub)?
> 
> I'll give it a little thought, but it's certainly doable.

Since impostors are generally referenced by port, would it make sense to create a `dict` with the port as the key? This way the user can modify a specific running impostor. Also, http://www.mbtest.org/docs/api/overview#add-stub provides a way to add a stub to an existing impostor. If the Impostors are retrieved from the running server, then this call can be used to add the stub while http://www.mbtest.org/docs/api/overview#delete-stub allows for the removal

**Comment by jbackman** [comment]
As for the method, why not add `MountebankServer.load_existing()` which could use `MountebankServer.query_all_imposters()` to populate the MountebankServer._running_imposters

**Comment by brunns** [comment]
So as of https://github.com/brunns/mbtest/commit/869b722685e6b6e82db6e0206b27557762ec6f2c we have `add_stub()` and `delete_stub()`. I was going to add something like `replace_all_stubs()` to `Impostor`, and call this one done.

But, it seems you'd also like the ability to retrieve an `Impostor` object for an already running server, right, so you can fiddle with its stubs?

**Comment by jbackman** [comment]
Yes - I was thinking of the following:

1. Retrieve all impostors from a running server and creating a dictionary of impostors with the port as the key that can be referenced
2. Store that dictionary so when cleanup is performed, you can return the Mountebank to its original configuration if desired
3. Allow per port addition of stubs at the beginning or removal of stubs in any position
4. Allow removal of Impostors from the running Mountebank
5. When all testing is complete, remove all added impostors or stubs and restore any impostors or stubs that were removed

**Comment by brunns** [comment]
Oh, I see - so it's not so much the stubs in an impostor you've like to retrieve and replace as it is the impostors in a server?

**Comment by jbackman** [comment]
It might help to explain my setup:

I have an existing Mountebank environment which already has a large number of Imposters loaded. In certain cases, I want to allow for adding new stubs to existing impostors overriding some of the built in responses, or removing existing impostors and stubs so that tests fail. It doesn't make sense to rewrite all of these imposters as fixtures that are loaded each time (especially since one of the imposters has > 40MB of data already loaded).

**Comment by jbackman** [comment]
I need to add/replace stubs and imposters. The existing implementation allows for the adding of new imposters and associated stubs, but not for the modification or removal of existing imposters and/or stubs.

**Comment by brunns** [comment]
OK, so `MountebankServer` has `query_all_imposters()`, `add_impostors()`, and `delete_imposters()` already. I could add a `delete_impostor()` method for a single impostor. Is that all you need there?

(Note that while `query_all_imposters()` doesn't return a `dict`, you could easily do `imposters = {i.port, i for i in query_all_imposters()}`, right?)

Then on `Impostor` we already have `add_stub()` and `delete_stub()`. alongside the `impostors` attribute, over which you can iterate.

What's still missing other than `delete_impostor()`?

**Comment by jbackman** [comment]
There needs to be a way populate the `_running_imposters` value otherwise, you would be recreating imposters every time you call MountebankServer. Also, there should be an update to the cleanup method that restores any removed impostors/stubs and removes and added imposters/stubs.

**Comment by brunns** [comment]
You can populate the `_running_imposters` attribute with `add_impostors()`, no?

And you could restore stuff by keeping references around and just adding them back?

If I'm still missing something, maybe you could show me the test you'd _like_ to be able to write?

**Comment by jbackman** [comment]
Wouldn't the add_impostors() when adding an existing impostor from the server itself cause an error?

https://github.com/brunns/mbtest/blob/master/src/mbtest/server.py#L148 seems to execute a post to the Mountebank server and if it exists, I believe it would return an error

**Comment by brunns** [comment]
Let me see. I'll try writing a test which retrieves the impostors from a running server, removes one, then put it back. Then a 2nd test which retrieves stubs from a running impostor, removes one, then puts that back.

**Comment by brunns** [comment]
I'll try and find some time tomorrow.

**Comment by brunns** [comment]
@jbackman Does https://github.com/brunns/mbtest/commit/09eedffb4993ef9035d8e209709f0e700da9ee2a#diff-b768c0081084c8ef7f0778657cd21d2d1bd75074c286d404a71dd7a9cf138b0bR110 look like it gives you the primitives you need?

**Comment by jbackman** [comment]
I will have to do some testing on this and am out for a week. My only concern is that the tests use the mockserver which I believe is a mountebank created using mbtest. This would not exercise the functionality of an external mountebank server.

**Comment by brunns** [comment]
Let me know what you find - I think it should work identically.

**Comment by jbackman** [comment]
I started testing today:

There is still no way to get the impostors already running in the  mountebank server into self._running_imposters. This means that although I can add and delete impostors I create, I can't modify the already running ones

**Comment by jbackman** [comment]
Maybe adding another function to the MountebankServer class like:

```
def import_running_imposters(self) -> None:
    for imposter in self.query_all_imposters():
        self._running_imposters.append(imposter)
```

**Comment by brunns** [comment]
How would https://github.com/brunns/mbtest/blob/master/tests/integration/test_server.py#L110 ideally look for you?

**Comment by jbackman** [comment]
The issue is that you create the stubs using the tooling which means you already have a record of it in the _running_imposters. If you use requests to create a dummy stub, it would be outside of the tooling and you would then be able to verify that you are importing what was on the server

**Comment by jbackman** [comment]
The two functions in the above PR allow you to import from a server and verify it was imported.

**Comment by jbackman** [comment]
I believe that with the added functions, I am now in a position to modify the existing mountebank server. There is only one potential issue ...

https://github.com/brunns/mbtest/blob/master/src/mbtest/server.py#L136
deletes imposters on exit, but if I imported from my exiting server, this would also remove the imposters that had originally been on the mountebank server. Maybe it would be a good idea to add a flag that when true, does not perform the delete and leaves it up to the user to clean up?

**Comment by brunns** [comment]
That should only happen if you're using the server as a context manager - in a `with` block. If you're attaching to a running server, and using its imposter definitions, there's no need to do that, since clearing out the impostors is the only thing the context manager stuff does.

**Comment by jbackman** [comment]
That is true... I think given the above, I'm good to close this out.

**Comment by brunns** [comment]
Released alpha 2.9.0a1 - let me know if it's good to release a production version.

**Comment by jbackman** [comment]
testing today

**Comment by jbackman** [comment]
I think it looks good to release

**Comment by brunns** [comment]
[2.9](https://pypi.org/project/mbtest/2.9.0/) released.
