### ISSUE TITLE
Look for Mountebank install as a default

### ISSUE THREAD

**Issue by jbackman** [brunns/mbtest#56]
Running integration tests fail because the mountebank installation must be installed in a specific location. 

The DEFAULT_MB_EXECUTABLE points to a location that doesn't always exist.

https://github.com/brunns/mbtest/pull/55 to fix this

**Comment by brunns** [comment]
Should be in the next release, but I'd like to finish off #54 before that.

**Comment by brunns** [comment]
[2.9](https://pypi.org/project/mbtest/2.9.0/) released.
