### ISSUE TITLE
Predicate jsonpath support

### ISSUE THREAD

**Issue by yevhen-m** [brunns/mbtest#73]
I can see you have `Predicate.xpath`, but there's no `jsonpath`. Any plans to add it?

**Comment by brunns** [comment]
I haven't needed it myself, but I'd have no objection at all to a PR for this.

**Comment by brunns** [comment]
If not, I'll try and get around to it, but no promises time-wise.

**Comment by yevhen-m** [comment]
Should be a matter of a few lines it looks like, I'll do it.

**Comment by brunns** [comment]
https://pypi.org/project/mbtest/#history released.
